# Generated by Django 5.2.8 on 2026-09-19 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medicalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('doctor', 'date', 'time'), name='unique_active_appointment_per_doctor_slot', violation_error_message='این پزشک در این تاریخ و ساعت قبلاً نوبت دارد. لطفاً تاریخ یا ساعت دیگری انتخاب کنید.'),
        ),
    ]
